
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  AuthState: typeof import("../../node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
  NuxtPicture: typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
  NaiveColorModeSwitch: typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveColorModeSwitch.vue")['default']
  NaiveConfig: typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveConfig.vue")['default']
  NaiveIcon: typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveIcon.vue")['default']
  NaiveNavbar: typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNavbar.vue")['default']
  NaiveTabbar: typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveTabbar.vue")['default']
  NaiveMenuLink: typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveMenuLink.vue")['default']
  NaiveLayoutSidebar: typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutSidebar.vue")['default']
  NaiveLayoutNavbar: typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutNavbar.vue")['default']
  NaiveDrawerLink: typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveDrawerLink.client.vue")['default']
  NaiveLoadingBar: typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLoadingBar.client.vue")['default']
  NaiveNotification: typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNotification.client.vue")['default']
  NThemeEditor: typeof import("naive-ui")['NThemeEditor']
  NAffix: typeof import("naive-ui")['NAffix']
  NAlert: typeof import("naive-ui")['NAlert']
  NAnchor: typeof import("naive-ui")['NAnchor']
  NAnchorLink: typeof import("naive-ui")['NAnchorLink']
  NAutoComplete: typeof import("naive-ui")['NAutoComplete']
  NAvatar: typeof import("naive-ui")['NAvatar']
  NAvatarGroup: typeof import("naive-ui")['NAvatarGroup']
  NBackTop: typeof import("naive-ui")['NBackTop']
  NBadge: typeof import("naive-ui")['NBadge']
  NBreadcrumb: typeof import("naive-ui")['NBreadcrumb']
  NBreadcrumbItem: typeof import("naive-ui")['NBreadcrumbItem']
  NButton: typeof import("naive-ui")['NButton']
  NButtonGroup: typeof import("naive-ui")['NButtonGroup']
  NCalendar: typeof import("naive-ui")['NCalendar']
  NCard: typeof import("naive-ui")['NCard']
  NCarousel: typeof import("naive-ui")['NCarousel']
  NCarouselItem: typeof import("naive-ui")['NCarouselItem']
  NCascader: typeof import("naive-ui")['NCascader']
  NCheckbox: typeof import("naive-ui")['NCheckbox']
  NCheckboxGroup: typeof import("naive-ui")['NCheckboxGroup']
  NCode: typeof import("naive-ui")['NCode']
  NCollapse: typeof import("naive-ui")['NCollapse']
  NCollapseItem: typeof import("naive-ui")['NCollapseItem']
  NCollapseTransition: typeof import("naive-ui")['NCollapseTransition']
  NColorPicker: typeof import("naive-ui")['NColorPicker']
  NConfigProvider: typeof import("naive-ui")['NConfigProvider']
  NCountdown: typeof import("naive-ui")['NCountdown']
  NDataTable: typeof import("naive-ui")['NDataTable']
  NDatePicker: typeof import("naive-ui")['NDatePicker']
  NDescriptions: typeof import("naive-ui")['NDescriptions']
  NDescriptionsItem: typeof import("naive-ui")['NDescriptionsItem']
  NDialog: typeof import("naive-ui")['NDialog']
  NDialogProvider: typeof import("naive-ui")['NDialogProvider']
  NDivider: typeof import("naive-ui")['NDivider']
  NDrawer: typeof import("naive-ui")['NDrawer']
  NDrawerContent: typeof import("naive-ui")['NDrawerContent']
  NDropdown: typeof import("naive-ui")['NDropdown']
  NDynamicInput: typeof import("naive-ui")['NDynamicInput']
  NDynamicTags: typeof import("naive-ui")['NDynamicTags']
  NElement: typeof import("naive-ui")['NElement']
  NEl: typeof import("naive-ui")['NEl']
  NEllipsis: typeof import("naive-ui")['NEllipsis']
  NPerformantEllipsis: typeof import("naive-ui")['NPerformantEllipsis']
  NEmpty: typeof import("naive-ui")['NEmpty']
  NEquation: typeof import("naive-ui")['NEquation']
  NFlex: typeof import("naive-ui")['NFlex']
  NFloatButton: typeof import("naive-ui")['NFloatButton']
  NFloatButtonGroup: typeof import("naive-ui")['NFloatButtonGroup']
  NForm: typeof import("naive-ui")['NForm']
  NFormItem: typeof import("naive-ui")['NFormItem']
  NFormItemCol: typeof import("naive-ui")['NFormItemCol']
  NFormItemGi: typeof import("naive-ui")['NFormItemGi']
  NFormItemGridItem: typeof import("naive-ui")['NFormItemGridItem']
  NFormItemRow: typeof import("naive-ui")['NFormItemRow']
  NGlobalStyle: typeof import("naive-ui")['NGlobalStyle']
  NGradientText: typeof import("naive-ui")['NGradientText']
  NGrid: typeof import("naive-ui")['NGrid']
  NGridItem: typeof import("naive-ui")['NGridItem']
  NGi: typeof import("naive-ui")['NGi']
  NHeatmap: typeof import("naive-ui")['NHeatmap']
  NHighlight: typeof import("naive-ui")['NHighlight']
  NIcon: typeof import("naive-ui")['NIcon']
  NIconWrapper: typeof import("naive-ui")['NIconWrapper']
  NImage: typeof import("naive-ui")['NImage']
  NImageGroup: typeof import("naive-ui")['NImageGroup']
  NImagePreview: typeof import("naive-ui")['NImagePreview']
  NInfiniteScroll: typeof import("naive-ui")['NInfiniteScroll']
  NInput: typeof import("naive-ui")['NInput']
  NInputGroup: typeof import("naive-ui")['NInputGroup']
  NInputGroupLabel: typeof import("naive-ui")['NInputGroupLabel']
  NInputNumber: typeof import("naive-ui")['NInputNumber']
  NInputOtp: typeof import("naive-ui")['NInputOtp']
  NLayout: typeof import("naive-ui")['NLayout']
  NLayoutContent: typeof import("naive-ui")['NLayoutContent']
  NLayoutFooter: typeof import("naive-ui")['NLayoutFooter']
  NLayoutHeader: typeof import("naive-ui")['NLayoutHeader']
  NLayoutSider: typeof import("naive-ui")['NLayoutSider']
  NCol: typeof import("naive-ui")['NCol']
  NRow: typeof import("naive-ui")['NRow']
  NLegacyTransfer: typeof import("naive-ui")['NLegacyTransfer']
  NList: typeof import("naive-ui")['NList']
  NListItem: typeof import("naive-ui")['NListItem']
  NLoadingBarProvider: typeof import("naive-ui")['NLoadingBarProvider']
  NLog: typeof import("naive-ui")['NLog']
  NMarquee: typeof import("naive-ui")['NMarquee']
  NMention: typeof import("naive-ui")['NMention']
  NMenu: typeof import("naive-ui")['NMenu']
  NMessageProvider: typeof import("naive-ui")['NMessageProvider']
  NModal: typeof import("naive-ui")['NModal']
  NModalProvider: typeof import("naive-ui")['NModalProvider']
  NNotificationProvider: typeof import("naive-ui")['NNotificationProvider']
  NNumberAnimation: typeof import("naive-ui")['NNumberAnimation']
  NPageHeader: typeof import("naive-ui")['NPageHeader']
  NPagination: typeof import("naive-ui")['NPagination']
  NPopconfirm: typeof import("naive-ui")['NPopconfirm']
  NPopover: typeof import("naive-ui")['NPopover']
  NPopselect: typeof import("naive-ui")['NPopselect']
  NProgress: typeof import("naive-ui")['NProgress']
  NQrCode: typeof import("naive-ui")['NQrCode']
  NRadio: typeof import("naive-ui")['NRadio']
  NRadioButton: typeof import("naive-ui")['NRadioButton']
  NRadioGroup: typeof import("naive-ui")['NRadioGroup']
  NRate: typeof import("naive-ui")['NRate']
  NResult: typeof import("naive-ui")['NResult']
  NScrollbar: typeof import("naive-ui")['NScrollbar']
  NSelect: typeof import("naive-ui")['NSelect']
  NSkeleton: typeof import("naive-ui")['NSkeleton']
  NSlider: typeof import("naive-ui")['NSlider']
  NSpace: typeof import("naive-ui")['NSpace']
  NSpin: typeof import("naive-ui")['NSpin']
  NSplit: typeof import("naive-ui")['NSplit']
  NStatistic: typeof import("naive-ui")['NStatistic']
  NStep: typeof import("naive-ui")['NStep']
  NSteps: typeof import("naive-ui")['NSteps']
  NSwitch: typeof import("naive-ui")['NSwitch']
  NTable: typeof import("naive-ui")['NTable']
  NTbody: typeof import("naive-ui")['NTbody']
  NTd: typeof import("naive-ui")['NTd']
  NTh: typeof import("naive-ui")['NTh']
  NThead: typeof import("naive-ui")['NThead']
  NTr: typeof import("naive-ui")['NTr']
  NTab: typeof import("naive-ui")['NTab']
  NTabPane: typeof import("naive-ui")['NTabPane']
  NTabs: typeof import("naive-ui")['NTabs']
  NTag: typeof import("naive-ui")['NTag']
  NThing: typeof import("naive-ui")['NThing']
  NTime: typeof import("naive-ui")['NTime']
  NTimePicker: typeof import("naive-ui")['NTimePicker']
  NTimeline: typeof import("naive-ui")['NTimeline']
  NTimelineItem: typeof import("naive-ui")['NTimelineItem']
  NTooltip: typeof import("naive-ui")['NTooltip']
  NTransfer: typeof import("naive-ui")['NTransfer']
  NTree: typeof import("naive-ui")['NTree']
  NTreeSelect: typeof import("naive-ui")['NTreeSelect']
  NA: typeof import("naive-ui")['NA']
  NBlockquote: typeof import("naive-ui")['NBlockquote']
  NH1: typeof import("naive-ui")['NH1']
  NH2: typeof import("naive-ui")['NH2']
  NH3: typeof import("naive-ui")['NH3']
  NH4: typeof import("naive-ui")['NH4']
  NH5: typeof import("naive-ui")['NH5']
  NH6: typeof import("naive-ui")['NH6']
  NHr: typeof import("naive-ui")['NHr']
  NLi: typeof import("naive-ui")['NLi']
  NOl: typeof import("naive-ui")['NOl']
  NP: typeof import("naive-ui")['NP']
  NText: typeof import("naive-ui")['NText']
  NUl: typeof import("naive-ui")['NUl']
  NUpload: typeof import("naive-ui")['NUpload']
  NUploadDragger: typeof import("naive-ui")['NUploadDragger']
  NUploadFileList: typeof import("naive-ui")['NUploadFileList']
  NUploadTrigger: typeof import("naive-ui")['NUploadTrigger']
  NVirtualList: typeof import("naive-ui")['NVirtualList']
  NWatermark: typeof import("naive-ui")['NWatermark']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyAuthState: LazyComponent<typeof import("../../node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
  LazyNaiveColorModeSwitch: LazyComponent<typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveColorModeSwitch.vue")['default']>
  LazyNaiveConfig: LazyComponent<typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveConfig.vue")['default']>
  LazyNaiveIcon: LazyComponent<typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveIcon.vue")['default']>
  LazyNaiveNavbar: LazyComponent<typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNavbar.vue")['default']>
  LazyNaiveTabbar: LazyComponent<typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveTabbar.vue")['default']>
  LazyNaiveMenuLink: LazyComponent<typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveMenuLink.vue")['default']>
  LazyNaiveLayoutSidebar: LazyComponent<typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutSidebar.vue")['default']>
  LazyNaiveLayoutNavbar: LazyComponent<typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutNavbar.vue")['default']>
  LazyNaiveDrawerLink: LazyComponent<typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveDrawerLink.client.vue")['default']>
  LazyNaiveLoadingBar: LazyComponent<typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLoadingBar.client.vue")['default']>
  LazyNaiveNotification: LazyComponent<typeof import("../../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNotification.client.vue")['default']>
  LazyNThemeEditor: LazyComponent<typeof import("naive-ui")['NThemeEditor']>
  LazyNAffix: LazyComponent<typeof import("naive-ui")['NAffix']>
  LazyNAlert: LazyComponent<typeof import("naive-ui")['NAlert']>
  LazyNAnchor: LazyComponent<typeof import("naive-ui")['NAnchor']>
  LazyNAnchorLink: LazyComponent<typeof import("naive-ui")['NAnchorLink']>
  LazyNAutoComplete: LazyComponent<typeof import("naive-ui")['NAutoComplete']>
  LazyNAvatar: LazyComponent<typeof import("naive-ui")['NAvatar']>
  LazyNAvatarGroup: LazyComponent<typeof import("naive-ui")['NAvatarGroup']>
  LazyNBackTop: LazyComponent<typeof import("naive-ui")['NBackTop']>
  LazyNBadge: LazyComponent<typeof import("naive-ui")['NBadge']>
  LazyNBreadcrumb: LazyComponent<typeof import("naive-ui")['NBreadcrumb']>
  LazyNBreadcrumbItem: LazyComponent<typeof import("naive-ui")['NBreadcrumbItem']>
  LazyNButton: LazyComponent<typeof import("naive-ui")['NButton']>
  LazyNButtonGroup: LazyComponent<typeof import("naive-ui")['NButtonGroup']>
  LazyNCalendar: LazyComponent<typeof import("naive-ui")['NCalendar']>
  LazyNCard: LazyComponent<typeof import("naive-ui")['NCard']>
  LazyNCarousel: LazyComponent<typeof import("naive-ui")['NCarousel']>
  LazyNCarouselItem: LazyComponent<typeof import("naive-ui")['NCarouselItem']>
  LazyNCascader: LazyComponent<typeof import("naive-ui")['NCascader']>
  LazyNCheckbox: LazyComponent<typeof import("naive-ui")['NCheckbox']>
  LazyNCheckboxGroup: LazyComponent<typeof import("naive-ui")['NCheckboxGroup']>
  LazyNCode: LazyComponent<typeof import("naive-ui")['NCode']>
  LazyNCollapse: LazyComponent<typeof import("naive-ui")['NCollapse']>
  LazyNCollapseItem: LazyComponent<typeof import("naive-ui")['NCollapseItem']>
  LazyNCollapseTransition: LazyComponent<typeof import("naive-ui")['NCollapseTransition']>
  LazyNColorPicker: LazyComponent<typeof import("naive-ui")['NColorPicker']>
  LazyNConfigProvider: LazyComponent<typeof import("naive-ui")['NConfigProvider']>
  LazyNCountdown: LazyComponent<typeof import("naive-ui")['NCountdown']>
  LazyNDataTable: LazyComponent<typeof import("naive-ui")['NDataTable']>
  LazyNDatePicker: LazyComponent<typeof import("naive-ui")['NDatePicker']>
  LazyNDescriptions: LazyComponent<typeof import("naive-ui")['NDescriptions']>
  LazyNDescriptionsItem: LazyComponent<typeof import("naive-ui")['NDescriptionsItem']>
  LazyNDialog: LazyComponent<typeof import("naive-ui")['NDialog']>
  LazyNDialogProvider: LazyComponent<typeof import("naive-ui")['NDialogProvider']>
  LazyNDivider: LazyComponent<typeof import("naive-ui")['NDivider']>
  LazyNDrawer: LazyComponent<typeof import("naive-ui")['NDrawer']>
  LazyNDrawerContent: LazyComponent<typeof import("naive-ui")['NDrawerContent']>
  LazyNDropdown: LazyComponent<typeof import("naive-ui")['NDropdown']>
  LazyNDynamicInput: LazyComponent<typeof import("naive-ui")['NDynamicInput']>
  LazyNDynamicTags: LazyComponent<typeof import("naive-ui")['NDynamicTags']>
  LazyNElement: LazyComponent<typeof import("naive-ui")['NElement']>
  LazyNEl: LazyComponent<typeof import("naive-ui")['NEl']>
  LazyNEllipsis: LazyComponent<typeof import("naive-ui")['NEllipsis']>
  LazyNPerformantEllipsis: LazyComponent<typeof import("naive-ui")['NPerformantEllipsis']>
  LazyNEmpty: LazyComponent<typeof import("naive-ui")['NEmpty']>
  LazyNEquation: LazyComponent<typeof import("naive-ui")['NEquation']>
  LazyNFlex: LazyComponent<typeof import("naive-ui")['NFlex']>
  LazyNFloatButton: LazyComponent<typeof import("naive-ui")['NFloatButton']>
  LazyNFloatButtonGroup: LazyComponent<typeof import("naive-ui")['NFloatButtonGroup']>
  LazyNForm: LazyComponent<typeof import("naive-ui")['NForm']>
  LazyNFormItem: LazyComponent<typeof import("naive-ui")['NFormItem']>
  LazyNFormItemCol: LazyComponent<typeof import("naive-ui")['NFormItemCol']>
  LazyNFormItemGi: LazyComponent<typeof import("naive-ui")['NFormItemGi']>
  LazyNFormItemGridItem: LazyComponent<typeof import("naive-ui")['NFormItemGridItem']>
  LazyNFormItemRow: LazyComponent<typeof import("naive-ui")['NFormItemRow']>
  LazyNGlobalStyle: LazyComponent<typeof import("naive-ui")['NGlobalStyle']>
  LazyNGradientText: LazyComponent<typeof import("naive-ui")['NGradientText']>
  LazyNGrid: LazyComponent<typeof import("naive-ui")['NGrid']>
  LazyNGridItem: LazyComponent<typeof import("naive-ui")['NGridItem']>
  LazyNGi: LazyComponent<typeof import("naive-ui")['NGi']>
  LazyNHeatmap: LazyComponent<typeof import("naive-ui")['NHeatmap']>
  LazyNHighlight: LazyComponent<typeof import("naive-ui")['NHighlight']>
  LazyNIcon: LazyComponent<typeof import("naive-ui")['NIcon']>
  LazyNIconWrapper: LazyComponent<typeof import("naive-ui")['NIconWrapper']>
  LazyNImage: LazyComponent<typeof import("naive-ui")['NImage']>
  LazyNImageGroup: LazyComponent<typeof import("naive-ui")['NImageGroup']>
  LazyNImagePreview: LazyComponent<typeof import("naive-ui")['NImagePreview']>
  LazyNInfiniteScroll: LazyComponent<typeof import("naive-ui")['NInfiniteScroll']>
  LazyNInput: LazyComponent<typeof import("naive-ui")['NInput']>
  LazyNInputGroup: LazyComponent<typeof import("naive-ui")['NInputGroup']>
  LazyNInputGroupLabel: LazyComponent<typeof import("naive-ui")['NInputGroupLabel']>
  LazyNInputNumber: LazyComponent<typeof import("naive-ui")['NInputNumber']>
  LazyNInputOtp: LazyComponent<typeof import("naive-ui")['NInputOtp']>
  LazyNLayout: LazyComponent<typeof import("naive-ui")['NLayout']>
  LazyNLayoutContent: LazyComponent<typeof import("naive-ui")['NLayoutContent']>
  LazyNLayoutFooter: LazyComponent<typeof import("naive-ui")['NLayoutFooter']>
  LazyNLayoutHeader: LazyComponent<typeof import("naive-ui")['NLayoutHeader']>
  LazyNLayoutSider: LazyComponent<typeof import("naive-ui")['NLayoutSider']>
  LazyNCol: LazyComponent<typeof import("naive-ui")['NCol']>
  LazyNRow: LazyComponent<typeof import("naive-ui")['NRow']>
  LazyNLegacyTransfer: LazyComponent<typeof import("naive-ui")['NLegacyTransfer']>
  LazyNList: LazyComponent<typeof import("naive-ui")['NList']>
  LazyNListItem: LazyComponent<typeof import("naive-ui")['NListItem']>
  LazyNLoadingBarProvider: LazyComponent<typeof import("naive-ui")['NLoadingBarProvider']>
  LazyNLog: LazyComponent<typeof import("naive-ui")['NLog']>
  LazyNMarquee: LazyComponent<typeof import("naive-ui")['NMarquee']>
  LazyNMention: LazyComponent<typeof import("naive-ui")['NMention']>
  LazyNMenu: LazyComponent<typeof import("naive-ui")['NMenu']>
  LazyNMessageProvider: LazyComponent<typeof import("naive-ui")['NMessageProvider']>
  LazyNModal: LazyComponent<typeof import("naive-ui")['NModal']>
  LazyNModalProvider: LazyComponent<typeof import("naive-ui")['NModalProvider']>
  LazyNNotificationProvider: LazyComponent<typeof import("naive-ui")['NNotificationProvider']>
  LazyNNumberAnimation: LazyComponent<typeof import("naive-ui")['NNumberAnimation']>
  LazyNPageHeader: LazyComponent<typeof import("naive-ui")['NPageHeader']>
  LazyNPagination: LazyComponent<typeof import("naive-ui")['NPagination']>
  LazyNPopconfirm: LazyComponent<typeof import("naive-ui")['NPopconfirm']>
  LazyNPopover: LazyComponent<typeof import("naive-ui")['NPopover']>
  LazyNPopselect: LazyComponent<typeof import("naive-ui")['NPopselect']>
  LazyNProgress: LazyComponent<typeof import("naive-ui")['NProgress']>
  LazyNQrCode: LazyComponent<typeof import("naive-ui")['NQrCode']>
  LazyNRadio: LazyComponent<typeof import("naive-ui")['NRadio']>
  LazyNRadioButton: LazyComponent<typeof import("naive-ui")['NRadioButton']>
  LazyNRadioGroup: LazyComponent<typeof import("naive-ui")['NRadioGroup']>
  LazyNRate: LazyComponent<typeof import("naive-ui")['NRate']>
  LazyNResult: LazyComponent<typeof import("naive-ui")['NResult']>
  LazyNScrollbar: LazyComponent<typeof import("naive-ui")['NScrollbar']>
  LazyNSelect: LazyComponent<typeof import("naive-ui")['NSelect']>
  LazyNSkeleton: LazyComponent<typeof import("naive-ui")['NSkeleton']>
  LazyNSlider: LazyComponent<typeof import("naive-ui")['NSlider']>
  LazyNSpace: LazyComponent<typeof import("naive-ui")['NSpace']>
  LazyNSpin: LazyComponent<typeof import("naive-ui")['NSpin']>
  LazyNSplit: LazyComponent<typeof import("naive-ui")['NSplit']>
  LazyNStatistic: LazyComponent<typeof import("naive-ui")['NStatistic']>
  LazyNStep: LazyComponent<typeof import("naive-ui")['NStep']>
  LazyNSteps: LazyComponent<typeof import("naive-ui")['NSteps']>
  LazyNSwitch: LazyComponent<typeof import("naive-ui")['NSwitch']>
  LazyNTable: LazyComponent<typeof import("naive-ui")['NTable']>
  LazyNTbody: LazyComponent<typeof import("naive-ui")['NTbody']>
  LazyNTd: LazyComponent<typeof import("naive-ui")['NTd']>
  LazyNTh: LazyComponent<typeof import("naive-ui")['NTh']>
  LazyNThead: LazyComponent<typeof import("naive-ui")['NThead']>
  LazyNTr: LazyComponent<typeof import("naive-ui")['NTr']>
  LazyNTab: LazyComponent<typeof import("naive-ui")['NTab']>
  LazyNTabPane: LazyComponent<typeof import("naive-ui")['NTabPane']>
  LazyNTabs: LazyComponent<typeof import("naive-ui")['NTabs']>
  LazyNTag: LazyComponent<typeof import("naive-ui")['NTag']>
  LazyNThing: LazyComponent<typeof import("naive-ui")['NThing']>
  LazyNTime: LazyComponent<typeof import("naive-ui")['NTime']>
  LazyNTimePicker: LazyComponent<typeof import("naive-ui")['NTimePicker']>
  LazyNTimeline: LazyComponent<typeof import("naive-ui")['NTimeline']>
  LazyNTimelineItem: LazyComponent<typeof import("naive-ui")['NTimelineItem']>
  LazyNTooltip: LazyComponent<typeof import("naive-ui")['NTooltip']>
  LazyNTransfer: LazyComponent<typeof import("naive-ui")['NTransfer']>
  LazyNTree: LazyComponent<typeof import("naive-ui")['NTree']>
  LazyNTreeSelect: LazyComponent<typeof import("naive-ui")['NTreeSelect']>
  LazyNA: LazyComponent<typeof import("naive-ui")['NA']>
  LazyNBlockquote: LazyComponent<typeof import("naive-ui")['NBlockquote']>
  LazyNH1: LazyComponent<typeof import("naive-ui")['NH1']>
  LazyNH2: LazyComponent<typeof import("naive-ui")['NH2']>
  LazyNH3: LazyComponent<typeof import("naive-ui")['NH3']>
  LazyNH4: LazyComponent<typeof import("naive-ui")['NH4']>
  LazyNH5: LazyComponent<typeof import("naive-ui")['NH5']>
  LazyNH6: LazyComponent<typeof import("naive-ui")['NH6']>
  LazyNHr: LazyComponent<typeof import("naive-ui")['NHr']>
  LazyNLi: LazyComponent<typeof import("naive-ui")['NLi']>
  LazyNOl: LazyComponent<typeof import("naive-ui")['NOl']>
  LazyNP: LazyComponent<typeof import("naive-ui")['NP']>
  LazyNText: LazyComponent<typeof import("naive-ui")['NText']>
  LazyNUl: LazyComponent<typeof import("naive-ui")['NUl']>
  LazyNUpload: LazyComponent<typeof import("naive-ui")['NUpload']>
  LazyNUploadDragger: LazyComponent<typeof import("naive-ui")['NUploadDragger']>
  LazyNUploadFileList: LazyComponent<typeof import("naive-ui")['NUploadFileList']>
  LazyNUploadTrigger: LazyComponent<typeof import("naive-ui")['NUploadTrigger']>
  LazyNVirtualList: LazyComponent<typeof import("naive-ui")['NVirtualList']>
  LazyNWatermark: LazyComponent<typeof import("naive-ui")['NWatermark']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
