
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AuthState: typeof import("../node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const NaiveColorModeSwitch: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveColorModeSwitch.vue")['default']
export const NaiveConfig: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveConfig.vue")['default']
export const NaiveIcon: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveIcon.vue")['default']
export const NaiveNavbar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNavbar.vue")['default']
export const NaiveTabbar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveTabbar.vue")['default']
export const NaiveMenuLink: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveMenuLink.vue")['default']
export const NaiveLayoutSidebar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutSidebar.vue")['default']
export const NaiveLayoutNavbar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutNavbar.vue")['default']
export const NaiveDrawerLink: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveDrawerLink.client.vue")['default']
export const NaiveLoadingBar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLoadingBar.client.vue")['default']
export const NaiveNotification: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNotification.client.vue")['default']
export const NThemeEditor: typeof import("naive-ui")['NThemeEditor']
export const NAffix: typeof import("naive-ui")['NAffix']
export const NAlert: typeof import("naive-ui")['NAlert']
export const NAnchor: typeof import("naive-ui")['NAnchor']
export const NAnchorLink: typeof import("naive-ui")['NAnchorLink']
export const NAutoComplete: typeof import("naive-ui")['NAutoComplete']
export const NAvatar: typeof import("naive-ui")['NAvatar']
export const NAvatarGroup: typeof import("naive-ui")['NAvatarGroup']
export const NBackTop: typeof import("naive-ui")['NBackTop']
export const NBadge: typeof import("naive-ui")['NBadge']
export const NBreadcrumb: typeof import("naive-ui")['NBreadcrumb']
export const NBreadcrumbItem: typeof import("naive-ui")['NBreadcrumbItem']
export const NButton: typeof import("naive-ui")['NButton']
export const NButtonGroup: typeof import("naive-ui")['NButtonGroup']
export const NCalendar: typeof import("naive-ui")['NCalendar']
export const NCard: typeof import("naive-ui")['NCard']
export const NCarousel: typeof import("naive-ui")['NCarousel']
export const NCarouselItem: typeof import("naive-ui")['NCarouselItem']
export const NCascader: typeof import("naive-ui")['NCascader']
export const NCheckbox: typeof import("naive-ui")['NCheckbox']
export const NCheckboxGroup: typeof import("naive-ui")['NCheckboxGroup']
export const NCode: typeof import("naive-ui")['NCode']
export const NCollapse: typeof import("naive-ui")['NCollapse']
export const NCollapseItem: typeof import("naive-ui")['NCollapseItem']
export const NCollapseTransition: typeof import("naive-ui")['NCollapseTransition']
export const NColorPicker: typeof import("naive-ui")['NColorPicker']
export const NConfigProvider: typeof import("naive-ui")['NConfigProvider']
export const NCountdown: typeof import("naive-ui")['NCountdown']
export const NDataTable: typeof import("naive-ui")['NDataTable']
export const NDatePicker: typeof import("naive-ui")['NDatePicker']
export const NDescriptions: typeof import("naive-ui")['NDescriptions']
export const NDescriptionsItem: typeof import("naive-ui")['NDescriptionsItem']
export const NDialog: typeof import("naive-ui")['NDialog']
export const NDialogProvider: typeof import("naive-ui")['NDialogProvider']
export const NDivider: typeof import("naive-ui")['NDivider']
export const NDrawer: typeof import("naive-ui")['NDrawer']
export const NDrawerContent: typeof import("naive-ui")['NDrawerContent']
export const NDropdown: typeof import("naive-ui")['NDropdown']
export const NDynamicInput: typeof import("naive-ui")['NDynamicInput']
export const NDynamicTags: typeof import("naive-ui")['NDynamicTags']
export const NElement: typeof import("naive-ui")['NElement']
export const NEl: typeof import("naive-ui")['NEl']
export const NEllipsis: typeof import("naive-ui")['NEllipsis']
export const NPerformantEllipsis: typeof import("naive-ui")['NPerformantEllipsis']
export const NEmpty: typeof import("naive-ui")['NEmpty']
export const NEquation: typeof import("naive-ui")['NEquation']
export const NFlex: typeof import("naive-ui")['NFlex']
export const NFloatButton: typeof import("naive-ui")['NFloatButton']
export const NFloatButtonGroup: typeof import("naive-ui")['NFloatButtonGroup']
export const NForm: typeof import("naive-ui")['NForm']
export const NFormItem: typeof import("naive-ui")['NFormItem']
export const NFormItemCol: typeof import("naive-ui")['NFormItemCol']
export const NFormItemGi: typeof import("naive-ui")['NFormItemGi']
export const NFormItemGridItem: typeof import("naive-ui")['NFormItemGridItem']
export const NFormItemRow: typeof import("naive-ui")['NFormItemRow']
export const NGlobalStyle: typeof import("naive-ui")['NGlobalStyle']
export const NGradientText: typeof import("naive-ui")['NGradientText']
export const NGrid: typeof import("naive-ui")['NGrid']
export const NGridItem: typeof import("naive-ui")['NGridItem']
export const NGi: typeof import("naive-ui")['NGi']
export const NHeatmap: typeof import("naive-ui")['NHeatmap']
export const NHighlight: typeof import("naive-ui")['NHighlight']
export const NIcon: typeof import("naive-ui")['NIcon']
export const NIconWrapper: typeof import("naive-ui")['NIconWrapper']
export const NImage: typeof import("naive-ui")['NImage']
export const NImageGroup: typeof import("naive-ui")['NImageGroup']
export const NImagePreview: typeof import("naive-ui")['NImagePreview']
export const NInfiniteScroll: typeof import("naive-ui")['NInfiniteScroll']
export const NInput: typeof import("naive-ui")['NInput']
export const NInputGroup: typeof import("naive-ui")['NInputGroup']
export const NInputGroupLabel: typeof import("naive-ui")['NInputGroupLabel']
export const NInputNumber: typeof import("naive-ui")['NInputNumber']
export const NInputOtp: typeof import("naive-ui")['NInputOtp']
export const NLayout: typeof import("naive-ui")['NLayout']
export const NLayoutContent: typeof import("naive-ui")['NLayoutContent']
export const NLayoutFooter: typeof import("naive-ui")['NLayoutFooter']
export const NLayoutHeader: typeof import("naive-ui")['NLayoutHeader']
export const NLayoutSider: typeof import("naive-ui")['NLayoutSider']
export const NCol: typeof import("naive-ui")['NCol']
export const NRow: typeof import("naive-ui")['NRow']
export const NLegacyTransfer: typeof import("naive-ui")['NLegacyTransfer']
export const NList: typeof import("naive-ui")['NList']
export const NListItem: typeof import("naive-ui")['NListItem']
export const NLoadingBarProvider: typeof import("naive-ui")['NLoadingBarProvider']
export const NLog: typeof import("naive-ui")['NLog']
export const NMarquee: typeof import("naive-ui")['NMarquee']
export const NMention: typeof import("naive-ui")['NMention']
export const NMenu: typeof import("naive-ui")['NMenu']
export const NMessageProvider: typeof import("naive-ui")['NMessageProvider']
export const NModal: typeof import("naive-ui")['NModal']
export const NModalProvider: typeof import("naive-ui")['NModalProvider']
export const NNotificationProvider: typeof import("naive-ui")['NNotificationProvider']
export const NNumberAnimation: typeof import("naive-ui")['NNumberAnimation']
export const NPageHeader: typeof import("naive-ui")['NPageHeader']
export const NPagination: typeof import("naive-ui")['NPagination']
export const NPopconfirm: typeof import("naive-ui")['NPopconfirm']
export const NPopover: typeof import("naive-ui")['NPopover']
export const NPopselect: typeof import("naive-ui")['NPopselect']
export const NProgress: typeof import("naive-ui")['NProgress']
export const NQrCode: typeof import("naive-ui")['NQrCode']
export const NRadio: typeof import("naive-ui")['NRadio']
export const NRadioButton: typeof import("naive-ui")['NRadioButton']
export const NRadioGroup: typeof import("naive-ui")['NRadioGroup']
export const NRate: typeof import("naive-ui")['NRate']
export const NResult: typeof import("naive-ui")['NResult']
export const NScrollbar: typeof import("naive-ui")['NScrollbar']
export const NSelect: typeof import("naive-ui")['NSelect']
export const NSkeleton: typeof import("naive-ui")['NSkeleton']
export const NSlider: typeof import("naive-ui")['NSlider']
export const NSpace: typeof import("naive-ui")['NSpace']
export const NSpin: typeof import("naive-ui")['NSpin']
export const NSplit: typeof import("naive-ui")['NSplit']
export const NStatistic: typeof import("naive-ui")['NStatistic']
export const NStep: typeof import("naive-ui")['NStep']
export const NSteps: typeof import("naive-ui")['NSteps']
export const NSwitch: typeof import("naive-ui")['NSwitch']
export const NTable: typeof import("naive-ui")['NTable']
export const NTbody: typeof import("naive-ui")['NTbody']
export const NTd: typeof import("naive-ui")['NTd']
export const NTh: typeof import("naive-ui")['NTh']
export const NThead: typeof import("naive-ui")['NThead']
export const NTr: typeof import("naive-ui")['NTr']
export const NTab: typeof import("naive-ui")['NTab']
export const NTabPane: typeof import("naive-ui")['NTabPane']
export const NTabs: typeof import("naive-ui")['NTabs']
export const NTag: typeof import("naive-ui")['NTag']
export const NThing: typeof import("naive-ui")['NThing']
export const NTime: typeof import("naive-ui")['NTime']
export const NTimePicker: typeof import("naive-ui")['NTimePicker']
export const NTimeline: typeof import("naive-ui")['NTimeline']
export const NTimelineItem: typeof import("naive-ui")['NTimelineItem']
export const NTooltip: typeof import("naive-ui")['NTooltip']
export const NTransfer: typeof import("naive-ui")['NTransfer']
export const NTree: typeof import("naive-ui")['NTree']
export const NTreeSelect: typeof import("naive-ui")['NTreeSelect']
export const NA: typeof import("naive-ui")['NA']
export const NBlockquote: typeof import("naive-ui")['NBlockquote']
export const NH1: typeof import("naive-ui")['NH1']
export const NH2: typeof import("naive-ui")['NH2']
export const NH3: typeof import("naive-ui")['NH3']
export const NH4: typeof import("naive-ui")['NH4']
export const NH5: typeof import("naive-ui")['NH5']
export const NH6: typeof import("naive-ui")['NH6']
export const NHr: typeof import("naive-ui")['NHr']
export const NLi: typeof import("naive-ui")['NLi']
export const NOl: typeof import("naive-ui")['NOl']
export const NP: typeof import("naive-ui")['NP']
export const NText: typeof import("naive-ui")['NText']
export const NUl: typeof import("naive-ui")['NUl']
export const NUpload: typeof import("naive-ui")['NUpload']
export const NUploadDragger: typeof import("naive-ui")['NUploadDragger']
export const NUploadFileList: typeof import("naive-ui")['NUploadFileList']
export const NUploadTrigger: typeof import("naive-ui")['NUploadTrigger']
export const NVirtualList: typeof import("naive-ui")['NVirtualList']
export const NWatermark: typeof import("naive-ui")['NWatermark']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAuthState: LazyComponent<typeof import("../node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
export const LazyNaiveColorModeSwitch: LazyComponent<typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveColorModeSwitch.vue")['default']>
export const LazyNaiveConfig: LazyComponent<typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveConfig.vue")['default']>
export const LazyNaiveIcon: LazyComponent<typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveIcon.vue")['default']>
export const LazyNaiveNavbar: LazyComponent<typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNavbar.vue")['default']>
export const LazyNaiveTabbar: LazyComponent<typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveTabbar.vue")['default']>
export const LazyNaiveMenuLink: LazyComponent<typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveMenuLink.vue")['default']>
export const LazyNaiveLayoutSidebar: LazyComponent<typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutSidebar.vue")['default']>
export const LazyNaiveLayoutNavbar: LazyComponent<typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutNavbar.vue")['default']>
export const LazyNaiveDrawerLink: LazyComponent<typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveDrawerLink.client.vue")['default']>
export const LazyNaiveLoadingBar: LazyComponent<typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLoadingBar.client.vue")['default']>
export const LazyNaiveNotification: LazyComponent<typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNotification.client.vue")['default']>
export const LazyNThemeEditor: LazyComponent<typeof import("naive-ui")['NThemeEditor']>
export const LazyNAffix: LazyComponent<typeof import("naive-ui")['NAffix']>
export const LazyNAlert: LazyComponent<typeof import("naive-ui")['NAlert']>
export const LazyNAnchor: LazyComponent<typeof import("naive-ui")['NAnchor']>
export const LazyNAnchorLink: LazyComponent<typeof import("naive-ui")['NAnchorLink']>
export const LazyNAutoComplete: LazyComponent<typeof import("naive-ui")['NAutoComplete']>
export const LazyNAvatar: LazyComponent<typeof import("naive-ui")['NAvatar']>
export const LazyNAvatarGroup: LazyComponent<typeof import("naive-ui")['NAvatarGroup']>
export const LazyNBackTop: LazyComponent<typeof import("naive-ui")['NBackTop']>
export const LazyNBadge: LazyComponent<typeof import("naive-ui")['NBadge']>
export const LazyNBreadcrumb: LazyComponent<typeof import("naive-ui")['NBreadcrumb']>
export const LazyNBreadcrumbItem: LazyComponent<typeof import("naive-ui")['NBreadcrumbItem']>
export const LazyNButton: LazyComponent<typeof import("naive-ui")['NButton']>
export const LazyNButtonGroup: LazyComponent<typeof import("naive-ui")['NButtonGroup']>
export const LazyNCalendar: LazyComponent<typeof import("naive-ui")['NCalendar']>
export const LazyNCard: LazyComponent<typeof import("naive-ui")['NCard']>
export const LazyNCarousel: LazyComponent<typeof import("naive-ui")['NCarousel']>
export const LazyNCarouselItem: LazyComponent<typeof import("naive-ui")['NCarouselItem']>
export const LazyNCascader: LazyComponent<typeof import("naive-ui")['NCascader']>
export const LazyNCheckbox: LazyComponent<typeof import("naive-ui")['NCheckbox']>
export const LazyNCheckboxGroup: LazyComponent<typeof import("naive-ui")['NCheckboxGroup']>
export const LazyNCode: LazyComponent<typeof import("naive-ui")['NCode']>
export const LazyNCollapse: LazyComponent<typeof import("naive-ui")['NCollapse']>
export const LazyNCollapseItem: LazyComponent<typeof import("naive-ui")['NCollapseItem']>
export const LazyNCollapseTransition: LazyComponent<typeof import("naive-ui")['NCollapseTransition']>
export const LazyNColorPicker: LazyComponent<typeof import("naive-ui")['NColorPicker']>
export const LazyNConfigProvider: LazyComponent<typeof import("naive-ui")['NConfigProvider']>
export const LazyNCountdown: LazyComponent<typeof import("naive-ui")['NCountdown']>
export const LazyNDataTable: LazyComponent<typeof import("naive-ui")['NDataTable']>
export const LazyNDatePicker: LazyComponent<typeof import("naive-ui")['NDatePicker']>
export const LazyNDescriptions: LazyComponent<typeof import("naive-ui")['NDescriptions']>
export const LazyNDescriptionsItem: LazyComponent<typeof import("naive-ui")['NDescriptionsItem']>
export const LazyNDialog: LazyComponent<typeof import("naive-ui")['NDialog']>
export const LazyNDialogProvider: LazyComponent<typeof import("naive-ui")['NDialogProvider']>
export const LazyNDivider: LazyComponent<typeof import("naive-ui")['NDivider']>
export const LazyNDrawer: LazyComponent<typeof import("naive-ui")['NDrawer']>
export const LazyNDrawerContent: LazyComponent<typeof import("naive-ui")['NDrawerContent']>
export const LazyNDropdown: LazyComponent<typeof import("naive-ui")['NDropdown']>
export const LazyNDynamicInput: LazyComponent<typeof import("naive-ui")['NDynamicInput']>
export const LazyNDynamicTags: LazyComponent<typeof import("naive-ui")['NDynamicTags']>
export const LazyNElement: LazyComponent<typeof import("naive-ui")['NElement']>
export const LazyNEl: LazyComponent<typeof import("naive-ui")['NEl']>
export const LazyNEllipsis: LazyComponent<typeof import("naive-ui")['NEllipsis']>
export const LazyNPerformantEllipsis: LazyComponent<typeof import("naive-ui")['NPerformantEllipsis']>
export const LazyNEmpty: LazyComponent<typeof import("naive-ui")['NEmpty']>
export const LazyNEquation: LazyComponent<typeof import("naive-ui")['NEquation']>
export const LazyNFlex: LazyComponent<typeof import("naive-ui")['NFlex']>
export const LazyNFloatButton: LazyComponent<typeof import("naive-ui")['NFloatButton']>
export const LazyNFloatButtonGroup: LazyComponent<typeof import("naive-ui")['NFloatButtonGroup']>
export const LazyNForm: LazyComponent<typeof import("naive-ui")['NForm']>
export const LazyNFormItem: LazyComponent<typeof import("naive-ui")['NFormItem']>
export const LazyNFormItemCol: LazyComponent<typeof import("naive-ui")['NFormItemCol']>
export const LazyNFormItemGi: LazyComponent<typeof import("naive-ui")['NFormItemGi']>
export const LazyNFormItemGridItem: LazyComponent<typeof import("naive-ui")['NFormItemGridItem']>
export const LazyNFormItemRow: LazyComponent<typeof import("naive-ui")['NFormItemRow']>
export const LazyNGlobalStyle: LazyComponent<typeof import("naive-ui")['NGlobalStyle']>
export const LazyNGradientText: LazyComponent<typeof import("naive-ui")['NGradientText']>
export const LazyNGrid: LazyComponent<typeof import("naive-ui")['NGrid']>
export const LazyNGridItem: LazyComponent<typeof import("naive-ui")['NGridItem']>
export const LazyNGi: LazyComponent<typeof import("naive-ui")['NGi']>
export const LazyNHeatmap: LazyComponent<typeof import("naive-ui")['NHeatmap']>
export const LazyNHighlight: LazyComponent<typeof import("naive-ui")['NHighlight']>
export const LazyNIcon: LazyComponent<typeof import("naive-ui")['NIcon']>
export const LazyNIconWrapper: LazyComponent<typeof import("naive-ui")['NIconWrapper']>
export const LazyNImage: LazyComponent<typeof import("naive-ui")['NImage']>
export const LazyNImageGroup: LazyComponent<typeof import("naive-ui")['NImageGroup']>
export const LazyNImagePreview: LazyComponent<typeof import("naive-ui")['NImagePreview']>
export const LazyNInfiniteScroll: LazyComponent<typeof import("naive-ui")['NInfiniteScroll']>
export const LazyNInput: LazyComponent<typeof import("naive-ui")['NInput']>
export const LazyNInputGroup: LazyComponent<typeof import("naive-ui")['NInputGroup']>
export const LazyNInputGroupLabel: LazyComponent<typeof import("naive-ui")['NInputGroupLabel']>
export const LazyNInputNumber: LazyComponent<typeof import("naive-ui")['NInputNumber']>
export const LazyNInputOtp: LazyComponent<typeof import("naive-ui")['NInputOtp']>
export const LazyNLayout: LazyComponent<typeof import("naive-ui")['NLayout']>
export const LazyNLayoutContent: LazyComponent<typeof import("naive-ui")['NLayoutContent']>
export const LazyNLayoutFooter: LazyComponent<typeof import("naive-ui")['NLayoutFooter']>
export const LazyNLayoutHeader: LazyComponent<typeof import("naive-ui")['NLayoutHeader']>
export const LazyNLayoutSider: LazyComponent<typeof import("naive-ui")['NLayoutSider']>
export const LazyNCol: LazyComponent<typeof import("naive-ui")['NCol']>
export const LazyNRow: LazyComponent<typeof import("naive-ui")['NRow']>
export const LazyNLegacyTransfer: LazyComponent<typeof import("naive-ui")['NLegacyTransfer']>
export const LazyNList: LazyComponent<typeof import("naive-ui")['NList']>
export const LazyNListItem: LazyComponent<typeof import("naive-ui")['NListItem']>
export const LazyNLoadingBarProvider: LazyComponent<typeof import("naive-ui")['NLoadingBarProvider']>
export const LazyNLog: LazyComponent<typeof import("naive-ui")['NLog']>
export const LazyNMarquee: LazyComponent<typeof import("naive-ui")['NMarquee']>
export const LazyNMention: LazyComponent<typeof import("naive-ui")['NMention']>
export const LazyNMenu: LazyComponent<typeof import("naive-ui")['NMenu']>
export const LazyNMessageProvider: LazyComponent<typeof import("naive-ui")['NMessageProvider']>
export const LazyNModal: LazyComponent<typeof import("naive-ui")['NModal']>
export const LazyNModalProvider: LazyComponent<typeof import("naive-ui")['NModalProvider']>
export const LazyNNotificationProvider: LazyComponent<typeof import("naive-ui")['NNotificationProvider']>
export const LazyNNumberAnimation: LazyComponent<typeof import("naive-ui")['NNumberAnimation']>
export const LazyNPageHeader: LazyComponent<typeof import("naive-ui")['NPageHeader']>
export const LazyNPagination: LazyComponent<typeof import("naive-ui")['NPagination']>
export const LazyNPopconfirm: LazyComponent<typeof import("naive-ui")['NPopconfirm']>
export const LazyNPopover: LazyComponent<typeof import("naive-ui")['NPopover']>
export const LazyNPopselect: LazyComponent<typeof import("naive-ui")['NPopselect']>
export const LazyNProgress: LazyComponent<typeof import("naive-ui")['NProgress']>
export const LazyNQrCode: LazyComponent<typeof import("naive-ui")['NQrCode']>
export const LazyNRadio: LazyComponent<typeof import("naive-ui")['NRadio']>
export const LazyNRadioButton: LazyComponent<typeof import("naive-ui")['NRadioButton']>
export const LazyNRadioGroup: LazyComponent<typeof import("naive-ui")['NRadioGroup']>
export const LazyNRate: LazyComponent<typeof import("naive-ui")['NRate']>
export const LazyNResult: LazyComponent<typeof import("naive-ui")['NResult']>
export const LazyNScrollbar: LazyComponent<typeof import("naive-ui")['NScrollbar']>
export const LazyNSelect: LazyComponent<typeof import("naive-ui")['NSelect']>
export const LazyNSkeleton: LazyComponent<typeof import("naive-ui")['NSkeleton']>
export const LazyNSlider: LazyComponent<typeof import("naive-ui")['NSlider']>
export const LazyNSpace: LazyComponent<typeof import("naive-ui")['NSpace']>
export const LazyNSpin: LazyComponent<typeof import("naive-ui")['NSpin']>
export const LazyNSplit: LazyComponent<typeof import("naive-ui")['NSplit']>
export const LazyNStatistic: LazyComponent<typeof import("naive-ui")['NStatistic']>
export const LazyNStep: LazyComponent<typeof import("naive-ui")['NStep']>
export const LazyNSteps: LazyComponent<typeof import("naive-ui")['NSteps']>
export const LazyNSwitch: LazyComponent<typeof import("naive-ui")['NSwitch']>
export const LazyNTable: LazyComponent<typeof import("naive-ui")['NTable']>
export const LazyNTbody: LazyComponent<typeof import("naive-ui")['NTbody']>
export const LazyNTd: LazyComponent<typeof import("naive-ui")['NTd']>
export const LazyNTh: LazyComponent<typeof import("naive-ui")['NTh']>
export const LazyNThead: LazyComponent<typeof import("naive-ui")['NThead']>
export const LazyNTr: LazyComponent<typeof import("naive-ui")['NTr']>
export const LazyNTab: LazyComponent<typeof import("naive-ui")['NTab']>
export const LazyNTabPane: LazyComponent<typeof import("naive-ui")['NTabPane']>
export const LazyNTabs: LazyComponent<typeof import("naive-ui")['NTabs']>
export const LazyNTag: LazyComponent<typeof import("naive-ui")['NTag']>
export const LazyNThing: LazyComponent<typeof import("naive-ui")['NThing']>
export const LazyNTime: LazyComponent<typeof import("naive-ui")['NTime']>
export const LazyNTimePicker: LazyComponent<typeof import("naive-ui")['NTimePicker']>
export const LazyNTimeline: LazyComponent<typeof import("naive-ui")['NTimeline']>
export const LazyNTimelineItem: LazyComponent<typeof import("naive-ui")['NTimelineItem']>
export const LazyNTooltip: LazyComponent<typeof import("naive-ui")['NTooltip']>
export const LazyNTransfer: LazyComponent<typeof import("naive-ui")['NTransfer']>
export const LazyNTree: LazyComponent<typeof import("naive-ui")['NTree']>
export const LazyNTreeSelect: LazyComponent<typeof import("naive-ui")['NTreeSelect']>
export const LazyNA: LazyComponent<typeof import("naive-ui")['NA']>
export const LazyNBlockquote: LazyComponent<typeof import("naive-ui")['NBlockquote']>
export const LazyNH1: LazyComponent<typeof import("naive-ui")['NH1']>
export const LazyNH2: LazyComponent<typeof import("naive-ui")['NH2']>
export const LazyNH3: LazyComponent<typeof import("naive-ui")['NH3']>
export const LazyNH4: LazyComponent<typeof import("naive-ui")['NH4']>
export const LazyNH5: LazyComponent<typeof import("naive-ui")['NH5']>
export const LazyNH6: LazyComponent<typeof import("naive-ui")['NH6']>
export const LazyNHr: LazyComponent<typeof import("naive-ui")['NHr']>
export const LazyNLi: LazyComponent<typeof import("naive-ui")['NLi']>
export const LazyNOl: LazyComponent<typeof import("naive-ui")['NOl']>
export const LazyNP: LazyComponent<typeof import("naive-ui")['NP']>
export const LazyNText: LazyComponent<typeof import("naive-ui")['NText']>
export const LazyNUl: LazyComponent<typeof import("naive-ui")['NUl']>
export const LazyNUpload: LazyComponent<typeof import("naive-ui")['NUpload']>
export const LazyNUploadDragger: LazyComponent<typeof import("naive-ui")['NUploadDragger']>
export const LazyNUploadFileList: LazyComponent<typeof import("naive-ui")['NUploadFileList']>
export const LazyNUploadTrigger: LazyComponent<typeof import("naive-ui")['NUploadTrigger']>
export const LazyNVirtualList: LazyComponent<typeof import("naive-ui")['NVirtualList']>
export const LazyNWatermark: LazyComponent<typeof import("naive-ui")['NWatermark']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
